application_version: v1.1.1
loader_version:
bin_folder:
isupdate: true
launch_game: false
game_path: C:\Program Files\Guild Wars 2
exe_name:
default_configuration:
  d3d9_wrapper: false
version:
  d3d9_wrapper:
installed:
  d3d9_wrapper:
disabled:
  d3d9_wrapper: false
